CREATE TABLE IF NOT EXISTS buckets (
  id SERIAL PRIMARY KEY,
  name VARCHAR(63) UNIQUE NOT NULL,
  region VARCHAR(20) NOT NULL DEFAULT 'us-east-1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_buckets_region ON buckets(region);
