const router = require('express').Router()
const ctrl = require('../controllers/awsController')

router.get('/health',                              ctrl.health)
router.get('/s3/buckets',                          ctrl.listBuckets)
router.post('/s3/buckets',                         ctrl.createBucket)
router.delete('/s3/buckets/:name',                 ctrl.deleteBucket)
router.get('/s3/buckets/:name/objects',            ctrl.listObjects)
router.post('/s3/buckets/:name/objects',           ctrl.putObject)
router.delete('/s3/buckets/:name/objects/*',       ctrl.deleteObject)
router.get('/s3/buckets/:name/download/*',         ctrl.getObject)
router.get('/s3/buckets/:name/view/*',             ctrl.viewObject)
router.get('/s3/buckets/:name/presigned/*',        ctrl.getPresignedUrl)
router.get('/s3/buckets/:name/versioning',         ctrl.getVersioning)
router.put('/s3/buckets/:name/versioning',         ctrl.putVersioning)
router.get('/s3/buckets/:name/versions',           ctrl.listVersions)
router.get('/s3/buckets/:name/policy',             ctrl.getBucketPolicy)
router.put('/s3/buckets/:name/policy',             ctrl.putBucketPolicy)
router.delete('/s3/buckets/:name/policy',          ctrl.deleteBucketPolicy)
router.get('/s3/buckets/:name/public-access',      ctrl.getPublicAccess)
router.put('/s3/buckets/:name/public-access',      ctrl.putPublicAccess)
router.get('/s3/buckets/:name/encryption',         ctrl.getEncryption)
router.put('/s3/buckets/:name/encryption',         ctrl.putEncryption)
router.get('/s3/buckets/:name/website',            ctrl.getWebsite)
router.put('/s3/buckets/:name/website',            ctrl.putWebsite)
router.delete('/s3/buckets/:name/website',         ctrl.deleteWebsite)
router.get('/s3/buckets/:name/tags',               ctrl.getBucketTags)
router.put('/s3/buckets/:name/tags',               ctrl.putBucketTags)
router.get('/s3/buckets/:name/ownership',          ctrl.getOwnership)
router.put('/s3/buckets/:name/ownership',          ctrl.putOwnership)
router.get('/s3/buckets/:name/object-lock',        ctrl.getObjectLock)
router.put('/s3/buckets/:name/object-lock',        ctrl.putObjectLock)
router.get('/s3/buckets/:name/lifecycle',          ctrl.getLifecycle)
router.put('/s3/buckets/:name/lifecycle',          ctrl.putLifecycle)
router.delete('/s3/buckets/:name/lifecycle',       ctrl.deleteLifecycle)
router.get('/ec2/instances',                       ctrl.describeInstances)
router.get('/lambda/functions',    ctrl.listFunctions)
router.get('/iam/users',           ctrl.listUsers)
router.get('/cloudwatch/metrics',  ctrl.listMetrics)
router.post('/cli',                ctrl.cliCommand)

module.exports = router
